(********************************************************************
 * COPYRIGHT -- Herbert Kannegiesser GmbH
 ********************************************************************
 * Program: svCPCache
 * File: svCPCacheExit.st
 * Author: hunholz
 * Created: March 29, 2012
 ********************************************************************
 * Implementation of program svCPCache
 ********************************************************************)

PROGRAM _EXIT


(* TODO : Add your code here *)


END_PROGRAM
