TYPE
  TCP_SERVER_STATE_ENUM : 
    (
    TCP_SERVER_IDLE := 1,
    TCP_SERVER_RECV := 2,
    TCP_SERVER_SEND := 3,
    TCP_SERVER_CLOSE := 4,
    TCP_SERVER_ERROR := 100
    );
  TCP_SOCKET_STATE_ENUM : 
    (
    TCP_SOCKET_OPEN := 0,
    TCP_SOCKET_LISTEN := 10,
    TCP_SOCKET_GET_CONNECTION_LIST := 50,
    TCP_SOCKET_CLOSE_ALL_CONNECTIONS := 51,
    TCP_SOCKET_SET_KEEP_ALIVE_ON := 61,
    TCP_SOCKET_SET_KEEP_ALIVE_CNT := 62,
    TCP_SOCKET_SET_KEEP_ALIVE_IDLE := 63,
    TCP_SOCKET_SET_KEEP_ALIVE_INTVL := 64,
    TCP_SOCKET_ERROR := 100
    );
  TCP_SERVER_FUB_TYP : 	STRUCT 
    TcpRecv : TcpRecv;
    TcpSend : TcpSend;
    TcpClose : TcpClose;
    Ton_NoData : TON;
  END_STRUCT;
  TCP_SERVER_TYP : 	STRUCT 
    State : TCP_SERVER_STATE_ENUM;
    Ident : UDINT;
    IpAddress : STRING[15];
    ResponsePort : UINT;
    RecieveData : ARRAY[0..TCP_RECV_BUFFER_SIZE]OF UINT;
    SendData : ARRAY[0..TCP_SEND_BUFFER_SIZE]OF UINT;
    Functions : TCP_SERVER_FUB_TYP;
  END_STRUCT;
END_TYPE
