
TYPE
	httpState_enum : 
		(
		HTTP_CLIENT_WAIT_FOR_COMMAND := 0,
		HTTP_CLIENT_PROCESS_REQUEST := 1,
		HTTP_CLIENT_PROCESS_ENABLE := 2,
		HTTP_CLIENT_PROCESS_SEND := 3,
		HTTP_CLIENT_PROCESS_WAIT_RESP := 4,
		HTTP_CLIENT_PROCESS_RESPONSE := 5,
		HTTP_CLIENT_COMPLETE := 6,
		HTTP_CLIENT_ABORT := 99
		);
END_TYPE
