(********************************************************************
 * COPYRIGHT -- Herbert Kannegiesser GmbH
 ********************************************************************
 * Program: mnTestUser
 * File: mnTestUserCyclic.st
 * Author: hunholz
 * Created: March 07, 2012
 ********************************************************************
 * Implementation of program mnTestUser
 ********************************************************************)

PROGRAM _CYCLIC


(* TODO : Add your code here *)


END_PROGRAM
