(********************************************************************
 * COPYRIGHT -- Herbert Kannegiesser GmbH
 ********************************************************************
 * Program: mnTest
 * File: mnTestExit.st
 * Author: hunholz
 * Created: March 03, 2012
 ********************************************************************
 * Implementation of program mnTest
 ********************************************************************)

PROGRAM _EXIT


(* TODO : Add your code here *)


END_PROGRAM
